### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by kam021m** [kam021m/kambot#2]
- [ ] Ban command
- [ ] multiple servers at one time operation(may come in kambot v2)
- [ ] update nugget and code
- [ ] user info extending
- [ ] upgrading command handler(may come in kambot v2)

**Comment by sutani217** [comment]
ok cum (you should say ok cummer)
